### ISSUE TITLE
10 Der User kann sich mit seiner E-Mail-Adresse und einem sicheren Passwort seiner Wahl registrieren.

### ISSUE THREAD

**Issue by spyringer** [jfuerlinger/htl-da-2021_22-feedback-app#20]
**To Improve**
- [ ] Passwort Mindestanforderungen festlegen
- [ ] Passwort Mindestanforderungen prüfen und Anforderungen anzeigen lassen

**Test:**
- [ ] Mirzet SQL Error ThunderClient (Registrierung funktioniert trotzdem?)
